name: Update Date & Time JSON

on:
  schedule:
    - cron: '0 */2 * * *'   # Every 2 hours UTC
  workflow_dispatch:

jobs:
  update-date-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update date-time JSON (UTC)
        run: |
          # Get current UTC time
          YEAR=$(date -u '+%Y')
          MONTH=$(date -u '+%m')
          DAY=$(date -u '+%d')
          HOUR=$(date -u '+%H')

          # Generate JSON
          echo "{\"year\": $YEAR, \"month\": \"$MONTH\", \"day\": $DAY, \"hour\": \"$HOUR\"}" > date.json
          cat date.json

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add date.json
          git diff --cached --quiet || git commit -m "Update date-time JSON [skip ci]"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
