name: Update Date & Time JSON

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours UTC
  workflow_dispatch:

jobs:
  update-date-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update date-time JSON (UTC)
        run: |
          # Get current UTC time
          YEAR=$(date -u '+%Y')
          MONTH=$(date -u '+%m')
          DAY=$(date -u '+%d')
          HOUR=$(date -u '+%H')

          # Generate JSON
          echo "{\"year\": \"$YEAR\", \"month\": \"$MONTH\", \"day\": \"$DAY\", \"hour\": \"$HOUR\"}" > date.json
          cat date.json

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update date-time JSON [skip ci]"
          file_pattern: "date.json"
